-- Pet Hotel – create per-service schemas
CREATE SCHEMA IF NOT EXISTS customer;
CREATE SCHEMA IF NOT EXISTS room;
CREATE SCHEMA IF NOT EXISTS booking;
CREATE SCHEMA IF NOT EXISTS amenity;
CREATE SCHEMA IF NOT EXISTS dining;
CREATE SCHEMA IF NOT EXISTS billing;
